### ISSUE TITLE
About ConVar Usage problem

### ISSUE THREAD

**Issue by bean312321** [redsunservers/SuperZombieFortress#106]
I want to use ConVar for disable Activate SZF for non-SZF maps
I’m use ConVat " sm_szf_force_on 0 " but not working.
When the replacement non-SZF map ,SZF message will still appear.
But !szf command cannot be used.
Players into the non-SZF map will become abnormal :
1. Players have no weapons.
2. But the player’s skin model is normal without a zombie model.
3. There are still zombie sound effects
I currently use the latest version of SZF

**Comment by gaejuck** [comment]
@bean312321

https://github.com/gaejuck/SuperZombieFortress

Use this, I made disable Activate SZF for non-SZF maps.

**Comment by gaejuck** [comment]
https://github.com/gaejuck/SuperZombieFortress/actions/runs/527759831
