### ISSUE TITLE
Add wiki page for list of available commands

### ISSUE THREAD

**Issue by some-username-here1** [redsunservers/SuperZombieFortress#109]
It isn't mentioned anywhere, and it would be nice to have a page dedicated to listing all of the commands for SZF. Maybe a few other additional pages too; such as a page dedicated on how to make and develop SZF maps.

**Comment by HeatRiser** [comment]
There is a mapping guide (albeit might need updated for a lot of changes) here: https://forum.redsun.tf/threads/how-to-map-for-szf-guide.820/

**Comment by some-username-here1** [comment]
Can there be a link somewhere in the README to that then?

**Comment by FortyTwoFortyTwo** [comment]
Guide was in redsun forum because SZF code was private during it, but I do agree to have GitHub wiki page as it public and allows any servers to run it.

**Comment by FortyTwoFortyTwo** [comment]
Done
