### ISSUE TITLE
New Plugin Link

### ISSUE THREAD

**Issue by Winterman981** [redsunservers/SuperZombieFortress#118]
Is there anywhere that I can obtain the original Super Zombie Fortress files, including the .smx plugin file?

This GitHub seems to not have it and the FastDL link on this page does nothing.

https://forums.alliedmods.net/showthread.php?p=1467101

**Comment by Joaquel** [comment]
I don't know what do you mean by original SZF files, but the plugin file in that page can be downloaded in that page, and the FastDL link works, but for some reason Alliedmodders handles some external pages very weird, so you need to copy thah link and paste it in your browser.

**Comment by infinitephantasm** [comment]
if you're looking for the github download for this plugin, [it's over here](https://github.com/redsunservers/SuperZombieFortress/releases/latest)

if you're looking for the very old outdated fastDL files that definitely won't work for whatever reason, you will need to copy paste this link in, visiting it from a new tab does not work on any site (`http://mechatheslag.net/tf2/SuperZombieFortress_Fastdl.zip`)

**Comment by HeatRiser** [comment]
As others have stated, there doesn't really seem to be an issue here. The plugin itself is downloadable and usable from the original AlliedModders forum post, and you can compile from the source on AlliedModders if you so wish.

If it's not for the Red Sun version fo SZF then it doesn't really belong here. You'd be better asking on the AlliedModders thread itself if it's to do with Mecha's original SZF code.
