### ISSUE TITLE
Medic losing 1 health per second when not at max health

### ISSUE THREAD

**Issue by eno26** [redsunservers/SuperZombieFortress#138]
A bit hard to explain but you can see what I mean in the video provided below

https://user-images.githubusercontent.com/58401639/225567248-6be75d7f-7a62-4e15-849b-c357e0cd8fa5.mp4

**Comment by FortyTwoFortyTwo** [comment]
This is intended as Medic have +3 HP regen by default, -1 to make it +2 overall. Ideally the default regen should be overridden instead of just stacking with our own regen, but it's not simple to do while having as few gamedatas as possible.

**Comment by eno26** [comment]
Yeah I was thrown off by that, anyway thanks for clarifying, gonna mark as closed
