### ISSUE TITLE
Server Crashes on specific occasions

### ISSUE THREAD

**Issue by Dr-Malpractice** [redsunservers/SuperZombieFortress#147]
Hello, I've run into this issue and have no idea why it keeps appearing.
The game crashes when:
- I force a tank or when a naturally spawned one comes
- I hurt a bot/kill a bot or when I kill bind
- when I switch classes
- and some other occassions that I might not know of yet.
Sourcemod and Metamod versions: 1.11
SZF mod version: Latest. (4.3.0)

Crash Log:
L 09/18/2023 - 15:39:59: SourceMod error session started
L 09/18/2023 - 15:39:59: Info (map "szf_streets_v1") (file "d:\tcafiles\users\<redacted>\6803728\tf\addons\sourcemod\logs\errors_20230918.log")
L 09/18/2023 - 15:39:59: [SM] Unable to load extension "tf2items.ext": The specified module could not be found.

L 09/18/2023 - 15:39:59: [superzombiefortress.smx] Failed to create detour: CGameUI::Deactivate
L 09/18/2023 - 15:43:39: SourceMod error session started
L 09/18/2023 - 15:43:39: Info (map "szf_streets_v1") (file "d:\tcafiles\users\<redacted>\6803728\tf\addons\sourcemod\logs\errors_20230918.log")
L 09/18/2023 - 15:43:39: [SM] Unable to load extension "tf2items.ext": The specified module could not be found.

L 09/18/2023 - 15:43:39: [superzombiefortress.smx] Failed to create detour: CGameUI::Deactivate

Any clues of it crashing?
Thanks in advance.

**Comment by FortyTwoFortyTwo** [comment]
Update SZF plugin to latest version, recent TF2 update fixed the crash from `CGameUI::Deactivate`, so the detour is no longer needed.

Though it might be possible that its not enough, as tf2items error shouldn't have appeared to begin with.
