### ISSUE TITLE
Special infected model floating on player death

### ISSUE THREAD

**Issue by TheWizardPomplamoose** [redsunservers/SuperZombieFortress#166]
Hey there! Playing around with setting up a dedicated SZF server and encountered a strange bug, when a special dies their worldmodel is left floating for a split second before disappearing. Is this part of the plugin or server settings? Using the latest build.

![image](https://github.com/user-attachments/assets/4a56ab02-a5b6-4235-95cb-499b3a68b5e4)

**Comment by Mikusch** [comment]
This typically happens when the model is not present as a file on the server.

**Comment by TheWizardPomplamoose** [comment]
That is very good to know thank you Mikusch! I'm extremely new to custom content for TF2 in general so if you don't mind me asking where would I put those files? Would I put them in /custom/models/ or put them in the root /tf/ directory, or somewhere else entirely?

**Comment by Mikusch** [comment]
You can put them in `tf/custom/models`, but that directory is only scanned on server start, so I advise putting them in `tf/models` instead. This should fix your issue.

**Comment by TheWizardPomplamoose** [comment]
Worked like a charm, thanks for your help Mikusch!
