### ISSUE TITLE
Sandvich still doing old damage effect at very close range

### ISSUE THREAD

**Issue by infinitephantasm** [redsunservers/SuperZombieFortress#28]
when tossing a sandvich at a survivor at point blank/very close range, it will behave like the older version (before the 'trap' change), and still do damage to the survivor with no wait time for picking it up.

i don't know if it's possible to prevent/make the sandvich not do that in such a short timespan (e.g. spawning to not being able to be picked up), but as far as i know, this is consistently possible to use and isn't really difficult to do at all.

**Comment by Kenzzer** [comment]
A `RequestFrame` + a ground flag check should be enough to achieve such a feature. Instead of arbitrarily re-enable touch after 3 seconds. Although on second thought It would be best to keep that time in case they shoot the sandwich at player's feet (directly on the ground), but not re-enable still if the sandwich is still in the air.

**Comment by FortyTwoFortyTwo** [comment]
Can't reproduce with sandvich. Make sure your using sandvich, as other food items still can be picked up in an instant (and deal less damage).

SDKHook for sandvich touch doesn't get enabled/detected until from a 3 seconds timer, so unless if there error into using other food items hook instead, or passing incorrect entity index.

**Comment by Kenzzer** [comment]
The health kit touch `MyTouch` is only triggered if `CItem::ItemTouch` is called. So your hook should work fine.
https://github.com/redsunservers/SuperZombieFortress/blob/5886179d819337f7bd022491750cdd8d1282198a/addons/sourcemod/scripting/superzombiefortress.sp#L4685-L4688

https://github.com/NicknineTheEagle/TF2-Base/blob/4977917e6123a1ba0f6ef6ceae400b3eed6840bd/src/game/server/item_world.cpp#L398

**Comment by FortyTwoFortyTwo** [comment]
@infinitephantasm this bug still happening?

**Comment by infinitephantasm** [comment]
haven't encountered in quite some time, so i'll just clsoe
