### ISSUE TITLE
Spy/Smoker doing unreduced backstab damage.

### ISSUE THREAD

**Issue by ste2rn** [redsunservers/SuperZombieFortress#38]
While under the effect of smoker's pull Survivor can get insta-backstabbed by smoker. I'm not sure if Spy or Stalker are able to deal full backstab damage though.

**Comment by haxtonsale** [comment]
https://github.com/redsunservers/SuperZombieFortress/blob/88454d1a3ede8d77e86d16bb7e8c94c96b14fc57/addons/sourcemod/scripting/superzombiefortress.sp#L840-L876

Backstabs should never ever deal more than 10 damage so idk what happened there

**Comment by FortyTwoFortyTwo** [comment]
My quick guess would be `IsRazorbackActive` returning true while not meant to be, or an error threw out somewhere, unable to return `Plugin_Changed` in time. Likely 2nd one

**Comment by FortyTwoFortyTwo** [comment]
Haven't heard anyone else getting this bug for 3 months, no clue what happened to this
