### ISSUE TITLE
Players with Razorback take normal damage from taunt kills

### ISSUE THREAD

**Issue by TuxoYKT** [redsunservers/SuperZombieFortress#61]
Any player with **active Razorback** will die instantly from taunt kills while any player **without or depleted** Razorback will just get stunned.

**Comment by FortyTwoFortyTwo** [comment]
Sounds similar to #38 but never knew it came from taunt kill, which that makes more sense now

**Comment by TuxoYKT** [comment]
I tried to add a check for the backstab in my commit. It seems works.
https://github.com/TuxoYKT/SuperZombieFortress/commit/c2bc2b286e61d634c048f5137817a51071f36164

**Comment by FortyTwoFortyTwo** [comment]
Yeah that commit seems good and makes sense, send a PR!
