### ISSUE TITLE
suggestions for batfox

### ISSUE THREAD

**Issue by Epicwindow** [redsunservers/SuperZombieFortress#66]
buff scout:
low hp
only good dps is scatterguns
melee sucks
speed isnt fast enough to always outrun zeds
double jump is useless in that server

+1 list for zombies so people dont keep complaing about being in zombie team for 5 rounds

last man stun resistance so he dont get raped so hard

some maps also makes weapon stucks peoples like volanic escape

make the weapon call better like:
somoene calls that they find a flreagun
pyro class can see where that man/flaregun is by outline and sound sfx

is demo boots a possible spawn?never saw one

zombie scout sandman cd is broken sometimes

**Comment by FortyTwoFortyTwo** [comment]
I couldn't really see any reason on why to buff scouts with your suggestions, but these may get changed in 4.0 anyway.

> last man stun resistance so he dont get raped so hard
This would possibly let last man unkillable with strong weapon, we never want that to happen.

> some maps also makes weapon stucks peoples like volanic escape
I'd like to disable collision on pickup weapons, but it need to stay on so plugin can detect there a weapon to pickup

> make the weapon call better like:
> somoene calls that they find a flreagun
> pyro class can see where that man/flaregun is by outline and sound sfx
Added outline on calling out rare weapon for 4.0 - https://github.com/redsunservers/SuperZombieFortress/commit/20ecc7df5cd498325e7d061b6afd8322f6ef9596
Not sure if more is needed from just this,but lets see how this goes first.

> is demo boots a possible spawn?never saw one
Nope, i tried to add it but weapon model don't have collision, meaning plugin couldn't detect and pickup.

> zombie scout sandman cd is broken sometimes
It does sometimes broke, but scout's goo is completely gone in 4.0 so you could say that is fixed.
