### ISSUE TITLE
Suggestion: 10 damage on Atomizer triple jump

### ISSUE THREAD

**Issue by Blazephlozard** [redsunservers/SuperZombieFortress#84]
Survivor Atomizer is cringe. The old balance of taking 10 damage on triple jump should be familiar to most players and prevent spamming it to avoid hits as a strategy.

**Comment by FortyTwoFortyTwo** [comment]
Valve removed the dmg taken on triple jump attrib, so a different penalty had to be done at https://github.com/redsunservers/SuperZombieFortress/pull/85
