### ISSUE TITLE
Super Zombie Fortress error 

### ISSUE THREAD

**Issue by Joaquel** [redsunservers/SuperZombieFortress#91]
L 07/26/2020 - 01:04:46: [superzombiefortress.smx] Unknown sound vo type "Fire" from infected "tank" in config

**Comment by FortyTwoFortyTwo** [comment]
Ho boy, `sounds.cfg` have it named "fire" full lowercase, but KeyValues read as "Fire" with an uppercase instead, because of how KeyValues cache works, ignoring case sensitive. Best simple solution is to just convert back to lowercase after reading config

**Comment by FortyTwoFortyTwo** [comment]
Should be fixed now, thanks for report!
